---
  - name: Cambiar configuración de Apache
    hosts: "{{groups['Origen'][0]}}"
    become: true
 
    tasks:
      - name: Cambiar configuración de un fichero
        replace:
          path: {{ Fichero }}   
          regexp: '{{ Conf1 }}'
          replace: '{{ Conf2 }}'
          
      - name: Reiniciar Apache2
        service: name=apache2 state=restarted

