---
- name: Sync Pull task - Executed on "{{groups['Origen'][0]}}"
  hosts: "{{groups['Origen'][0]}}"
  tasks:   
    - name: Copy the file from Ubuntu to CentOs using Method Pull
      tags: sync-pull
      synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: pull
      delegate_to: "{{groups['Destino'][0]}}"
      register: syncfile
      run_once: true
