---
- name: Sync Pull task - Executed on "{{all[0]}}"
  hosts: all
  tasks:   
    - name: Copy the file from Ubuntu to CentOs using Method Pull
      tags: sync-pull
      synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: pull
      delegate_to: "{all[1]}}"
      register: syncfile
      run_once: true
      with_items:
       - "/tmp/pruebaUbuntu.txt"

- name: Sync Pull task - Executed on "{{all[1]}}"
  hosts: all
  tasks:
    - name: Copy the file from Ubuntu to CentOs   
      tags: sync-push
      synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: pull
      delegate_to: "{all[0]}}"
      register: syncfile
      with_items:
       - "/tmp/pruebaCentOs.txt"

