---
- name: Sync Pull task - Executed on "{{groups['app'][0]}}"
  hosts: "{{groups['app'][0]}}"
  tasks:   
    - name: Copy the file from Ubuntu to CentOs using Method Pull
      tags: sync-pull
      synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: pull
      delegate_to: "{{groups['app'][1]}}"
      register: syncfile
      run_once: true
      with_items:
       - "/tmp/pruebaUbuntu.txt"

- name: Sync Push task - Executed on "{{groups['app'][1]}}"
  hosts: "{{groups['app'][1]}}" 
  user: awx_gcp
  tasks:
    - name: Copy the file from Ubuntu to CentOs   
      tags: sync-push
      synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: pull
      delegate_to: "{{groups['app'][0]}}"
      register: syncfile
      with_items:
       - "/tmp/pruebaCentOs.txt"
