---
- name:Executed on "{{groups['Origen'][0]}}"
  hosts: "{{groups['Origen'][0]}}"
  tasks:
    - name: Copy the file from "{{groups['Origen'][0]}}" to "{{groups['Destino'][0]}}"
      tags: sync-pull
      synchronize:
        src: "{{ itemO }}"
        dest: "{{ itemD }}"
        mode: pull
      delegate_to: "{{groups['Destino'][0]}}"
      register: syncfile
      run_once: true

